kind: ConfigMap
apiVersion: v1
metadata:
  name: backstage-config-backend-auth
  namespace: rhdh-operator
data:
  app-config.backend-auth.yaml: |
    backend:
      auth:
        environment: production
        keys:
          - secret: "changeme"
    auth:
      environment: production
      providers:
        github:
          production:
            clientId: "changeme"
            clientSecret: "changeme"

