kind: Secret
apiVersion: v1
metadata:
  name: secrets-rhdh
  namespace: rhdh-operator
  labels:
    rhdh.redhat.com/ext-config-sync: 'true'
  annotations:
    rhdh.redhat.com/backstage-name: developer-hub
data:
  BACKEND_SECRET: changeme
type: Opaque

